import fs from "node:fs";
import path from "node:path";

export class NextjsConverter {
  get name() { return "nextjs"; }
  get displayName() { return "Next.js (App Router)"; }

  async convert(sourceDir, workDir) {
    const projectName = path.basename(workDir);

    // 1. Create Next.js directory structure
    const appDir = path.join(workDir, "app");
    const componentsDir = path.join(workDir, "components");
    const publicDir = path.join(workDir, "public");
    for (const d of [appDir, componentsDir, publicDir]) {
      fs.mkdirSync(d, { recursive: true });
    }

    // 2. Generate next.config.ts
    fs.writeFileSync(path.join(workDir, "next.config.ts"), this._generateNextConfig(), "utf8");

    // 3. Detect globals.css
    const srcIndexCss = path.join(sourceDir, "src", "index.css");
    const srcGlobalsCss = path.join(sourceDir, "src", "globals.css");
    let hasGlobalCss = false;

    if (fs.existsSync(srcIndexCss)) {
      fs.copyFileSync(srcIndexCss, path.join(appDir, "globals.css"));
      hasGlobalCss = true;
    } else if (fs.existsSync(srcGlobalsCss)) {
      fs.copyFileSync(srcGlobalsCss, path.join(appDir, "globals.css"));
      hasGlobalCss = true;
    }

    // 4. Generate app/layout.tsx
    fs.writeFileSync(path.join(appDir, "layout.tsx"), this._generateLayout(hasGlobalCss), "utf8");

    // 5. Convert src/App.tsx -> app/page.tsx
    const srcApp = path.join(sourceDir, "src", "App.tsx");
    const srcAppJsx = path.join(sourceDir, "src", "App.jsx");
    let appContent = null;

    if (fs.existsSync(srcApp)) {
      appContent = fs.readFileSync(srcApp, "utf8");
    } else if (fs.existsSync(srcAppJsx)) {
      appContent = fs.readFileSync(srcAppJsx, "utf8");
    }

    if (appContent !== null) {
      const pageContent = this._convertAppToPage(appContent);
      fs.writeFileSync(path.join(appDir, "page.tsx"), pageContent, "utf8");
    } else {
      // Fallback empty page
      fs.writeFileSync(
        path.join(appDir, "page.tsx"),
        `"use client";\n\nexport default function Page() {\n  return <div>Hello from Next.js</div>;\n}\n`,
        "utf8"
      );
    }

    // 6. Copy src/components/* -> components/*
    const srcComponents = path.join(sourceDir, "src", "components");
    if (fs.existsSync(srcComponents)) {
      this._copyDir(srcComponents, componentsDir);
    }

    // 7. Copy public/ if exists
    const srcPublic = path.join(sourceDir, "public");
    if (fs.existsSync(srcPublic)) {
      this._copyDir(srcPublic, publicDir);
    }

    // 8. Generate tsconfig.json
    fs.writeFileSync(
      path.join(workDir, "tsconfig.json"),
      JSON.stringify(this._generateTsConfig(), null, 2) + "\n",
      "utf8"
    );

    // 9. Generate postcss.config.mjs
    fs.writeFileSync(path.join(workDir, "postcss.config.mjs"), this._generatePostcssConfig(), "utf8");

    // 10. Generate package.json
    fs.writeFileSync(
      path.join(workDir, "package.json"),
      JSON.stringify(this._generatePackageJson(projectName), null, 2) + "\n",
      "utf8"
    );

    // 11. Generate .gitignore
    fs.writeFileSync(
      path.join(workDir, ".gitignore"),
      "node_modules\n.next\n.env.local\n",
      "utf8"
    );
  }

  _convertAppToPage(content) {
    // Add "use client" directive if not already present
    let result = content;
    if (!result.includes('"use client"') && !result.includes("'use client'")) {
      result = `"use client";\n\n${result}`;
    }

    // Rename default export function to Page if it's named App
    result = result.replace(/export\s+default\s+function\s+App\s*\(/, "export default function Page(");

    // Remove Vite-specific imports (e.g. import styles from './App.module.css' is fine, but vite assets)
    result = result.replace(/import\s+\S+\s+from\s+["'][^"']+\.svg["'];?\n?/g, "");

    return result;
  }

  _generatePackageJson(projectName) {
    return {
      name: projectName,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "^15.0.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
      },
      devDependencies: {
        typescript: "^5.7.0",
        "@types/node": "^22.0.0",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        tailwindcss: "^4.0.0",
        "@tailwindcss/postcss": "^4.0.0",
      },
    };
  }

  _generateNextConfig() {
    return `import type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;\n`;
  }

  _generateLayout(hasGlobalCss) {
    return `import type { Metadata } from "next";
${hasGlobalCss ? 'import "./globals.css";' : ""}

export const metadata: Metadata = {
  title: "Gemini Export",
  description: "Generated by Gemini Design Agent",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
  }

  _generatePostcssConfig() {
    return `export default {\n  plugins: {\n    "@tailwindcss/postcss": {},\n  },\n};\n`;
  }

  _generateTsConfig() {
    return {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    };
  }

  _copyDir(src, dest) {
    fs.mkdirSync(dest, { recursive: true });
    for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
      const srcPath = path.join(src, entry.name);
      const destPath = path.join(dest, entry.name);
      if (entry.isDirectory()) {
        this._copyDir(srcPath, destPath);
      } else {
        fs.copyFileSync(srcPath, destPath);
      }
    }
  }
}
